name: push
on: [ push ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lint
        run: docker-compose up --abort-on-container-exit lint
